site:
  title: E-Commerce Solutions GitDocs
  start_page: home::index.adoc
content:
  sources:
    - url: https://github.com/dominikcebula/gitdocs-sample-component-home.git
      branches: HEAD
    - url: https://github.com/dominikcebula/gitdocs-sample-component-example.git
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
